version: '3.2'

services:
  apigw-starting:
    image: eu.gcr.io/techops-infradel/platform-api-gateway:0.13-1
    build:
      context: .
      dockerfile: starting.Dockerfile
    environment:
      - KONG_PG_HOST=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_CUSTOM_PLUGINS=okta-auth,stdout-log
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444

  apigw-processing:
    image: eu.gcr.io/techops-infradel/platform-api-gateway:0.14
    build:
      context: .
      dockerfile: processing.Dockerfile
    environment:
      - KONG_PG_HOST=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_CUSTOM_PLUGINS=okta-auth,stdout-log
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444

  apigw-finishing:
    image: eu.gcr.io/techops-infradel/platform-api-gateway:1.03
    build:
      context: .
      dockerfile: finishing.Dockerfile
    environment:
      - KONG_PG_HOST=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_CUSTOM_PLUGINS=okta-auth,stdout-log
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444