version: '3.2'

services:
  apigw-starting:
    image: eu.gcr.io/techops-infradel/platform-api-gateway:0.13-1
    build:
      context: .
      dockerfile: dockerfile/starting.Dockerfile
    environment:
      - KONG_PG_HOST=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_CUSTOM_PLUGINS=okta-auth,stdout-log
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444

  apigw-processing:
    image: eu.gcr.io/techops-infradel/platform-api-gateway:0.14
    build:
      context: .
      dockerfile: dockerfile/processing.Dockerfile
    environment:
      - KONG_DATABASE=kong
      - KONG_PG_USER=postgres
      - KONG_PG_PASSWORD=rwIf1xgen5accG40
      - KONG_PG_DATABASE=kong
      - KONG_PG_HOST=35.240.88.144
      - KONG_PG_PORT=5432
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_CUSTOM_PLUGINS=okta-auth,stdout-log
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444

  apigw-finishing:
    image: eu.gcr.io/techops-infradel/platform-api-gateway:1.03
    build:
      context: .
      dockerfile: dockerfile/finishing.Dockerfile
    environment:
      - KONG_DATABASE=kong
      - KONG_PG_USER=postgres
      - KONG_PG_PASSWORD=rwIf1xgen5accG40
      - KONG_PG_DATABASE=kong
      - KONG_PG_HOST=35.241.230.16
      - KONG_PG_PORT=5432
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_CUSTOM_PLUGINS=okta-auth,stdout-log
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444